import { Link } from "react-router";
import { motion } from "framer-motion";
import {
  ArrowRight,
  ArrowUpRight,
  Check,
  FileText,
  Briefcase,
  Code2,
  Sparkles,
  ShieldCheck,
  Bot,
  Users,
  Building2,
} from "lucide-react";
import { NyrNav, NyrFooter } from "@/components/NyrLayout";

const reveal = {
  initial: { opacity: 0, y: 18 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-60px" },
  transition: { duration: 0.55, ease: "easeOut" as const },
};

const rubric = [
  {
    icon: FileText,
    name: "Resume",
    weight: "30 pts",
    body: "Trajectory, impact, and signal — not keyword soup. We read every line ourselves and look for people who shipped things that mattered.",
  },
  {
    icon: Briefcase,
    name: "Experience",
    weight: "30 pts",
    body: "Where they've worked, what they owned, and how long they stayed. Real companies, real responsibility, real results.",
  },
  {
    icon: Code2,
    name: "Technical skills",
    weight: "40 pts",
    body: "The heaviest slice. Hands-on evaluation of what they can actually build — informed by our own AI systems work, so the bar is a working bar.",
  },
];

const steps = [
  {
    n: "01",
    title: "Find",
    body: "We post the role and hunt down candidates ourselves — human recruiters doing real sourcing, not keyword filters. Every pipeline is built by hand for the specific role.",
  },
  {
    n: "02",
    title: "Score",
    body: "Every single candidate gets scored on our comprehensive 100-point scale: resume, work experience, and technical skills. No exceptions, no gut feelings.",
  },
  {
    n: "03",
    title: "Send",
    body: "Only candidates scoring 90+ reach your team. Everyone else never makes it past us — your inbox stays clean, your time stays yours.",
  },
  {
    n: "04",
    title: "Support",
    body: "We stay in the loop through interviews and offer. If AI can automate part of the work instead of hiring for it, we'll build that too.",
  },
];

const audiences = [
  {
    icon: Building2,
    title: "Startups hiring now",
    body: "You need great people fast, but don't have the time or pipeline to sort hundreds of resumes. We handle the hunt and hand you a shortlist of only the strongest candidates.",
    points: [
      "No in-house recruiter needed — we are your recruiting team",
      "3 to 5 pre-scored candidates instead of a pile of maybes",
      "Full scorecards attached so you know why each person made the cut",
      "Works for engineering, ops, GTM — any role you'd trust a human with",
    ],
    cta: { label: "Start hiring", to: "/partner" },
  },
  {
    icon: Users,
    title: "Founders who've been burned",
    body: "You've tried job boards, agencies, and AI tools. What showed up was noise. We built our scoring system so we could promise a bar instead of a volume discount.",
    points: [
      "A published 100-point rubric, applied the same way to everyone",
      "If AI can do part of the role, we'll tell you before you hire for it",
      "One flat conversation about the role — not a sales funnel",
      "We benchmark enterprise AI ourselves, so our bar is a working bar",
    ],
    cta: { label: "Partner with us", to: "/partner" },
  },
];

const aiPoints = [
  {
    icon: Bot,
    title: "We build enterprise AI",
    body: "Custom agents and automation for real business workflows — deployed, monitored, and owned by you. Not demos. Systems that survive production.",
  },
  {
    icon: ShieldCheck,
    title: "We test AI honestly",
    body: "Independent benchmarks across industries. Real simulations, pass rates, failure analysis. If an AI can't do the job, we publish that too.",
  },
  {
    icon: Sparkles,
    title: "It sharpens our hiring",
    body: "Because we build and evaluate AI systems ourselves, we know exactly what 'great' looks like — and we score every candidate against that same bar.",
  },
];

const faqs = [
  {
    q: "What does the 100-point scale actually measure?",
    a: "Three things, weighted: resume (30), work experience (30), and technical skills (40). Every candidate is scored on all three by a human recruiter, and you see the full breakdown for anyone we send you.",
  },
  {
    q: "Why only 90+?",
    a: "Because you don't need more candidates — you need the right ones. Filtering to 90+ means we send you a handful of people worth meeting instead of a pile of maybes. Fewer interviews, faster hires, better outcomes.",
  },
  {
    q: "How is this different from an AI recruiter tool?",
    a: "It's the opposite. Real humans source and read every candidate. We use AI systems on the evaluation side — built and tested in-house — to make our scoring sharper, not to spam you with autogenerated matches.",
  },
  {
    q: "What if we don't need a hire at all?",
    a: "That's the other half of our business. We build and test enterprise AI systems, and sometimes the honest answer is that part of the role can be automated. We'll tell you which, and build it if you want.",
  },
  {
    q: "How do we get started?",
    a: "Tell us about the role through the partner form. We build the pipeline, start scoring, and your first 90+ candidates typically arrive within days — with the full scorecard attached.",
  },
];

export default function Landing() {
  return (
    <div className="nyr min-h-screen bg-background">
      {/* ============ NAV ============ */}
      <NyrNav />

      {/* ============ HERO (dark) ============ */}
      <section className="relative overflow-hidden bg-[#0e1730] text-[#ffffff]">
        <div className="nyr-grid-noise absolute inset-0" />
        <div
          className="absolute inset-0"
          style={{
            background:
              "radial-gradient(ellipse 60% 45% at 78% 12%, rgba(46,107,239,.22), transparent 60%)",
          }}
        />
        <div className="relative mx-auto grid min-h-[calc(100svh-68px)] max-w-6xl items-center gap-12 px-4 py-24 sm:px-6 lg:grid-cols-[1.05fr_.75fr] lg:py-16">
          <div>
            <motion.div {...reveal} className="nyr-eyebrow mb-6">
              <span className="nyr-status-dot" />
              Recruitment for the AI era
            </motion.div>

            <motion.h1
              {...reveal}
              transition={{ duration: 0.55, delay: 0.08, ease: "easeOut" }}
              className="nyr-display mb-6"
            >
              We find the best people <em>for the job.</em>
            </motion.h1>

            <motion.p
              {...reveal}
              transition={{ duration: 0.55, delay: 0.14, ease: "easeOut" }}
              className="nyr-lede max-w-[52ch]"
            >
              Streamscale hunts down top candidates, scores every one on a
              100-point scale — resume, experience, technical skills — and only
              sends you the 90+. We also build and test enterprise AI systems,
              so we know exactly what great looks like.
            </motion.p>

            <motion.div
              {...reveal}
              transition={{ duration: 0.55, delay: 0.2, ease: "easeOut" }}
              className="mt-8 flex flex-wrap items-center gap-6"
            >
              <Link to="/partner" className="nyr-primary-btn">
                Find your next hire <ArrowRight className="size-4" />
              </Link>
              <a href="#scoring" className="nyr-text-link">
                See how we score <span aria-hidden>↓</span>
              </a>
            </motion.div>

            <motion.div
              {...reveal}
              transition={{ duration: 0.55, delay: 0.26, ease: "easeOut" }}
              className="nyr-signal mt-12 flex flex-wrap gap-x-8 gap-y-2"
            >
              <span>Humans placed by humans.</span>
              <span>Only 90+ scorers reach your team.</span>
            </motion.div>
          </div>

          {/* Stage visual */}
          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.7, delay: 0.15, ease: "easeOut" }}
            className="relative hidden min-h-[480px] place-items-center lg:grid"
          >
            <div className="nyr-halo" />
            <div className="relative w-full max-w-xs rounded-2xl border border-[#dce6f7]/20 bg-[#0e1730]/95 p-5 shadow-[0_30px_90px_rgba(0,0,0,0.35)]">
              <div className="flex items-center justify-between text-[0.63rem] text-[#ffffff]/60">
                <span>9:41</span>
                <span>● ● ●</span>
              </div>
              <p className="mt-6 text-[0.62rem] font-extrabold uppercase tracking-[0.12em] text-[#7aa5f0]">
                Candidate scorecard
              </p>
              <h3 className="mt-2 text-xl font-semibold leading-snug text-[#ffffff]">
                Senior AI Engineer
              </h3>
              <div className="mt-4 space-y-2.5">
                {[
                  ["Resume", 94],
                  ["Experience", 92],
                  ["Technical", 96],
                ].map(([label, score]) => (
                  <div key={label as string}>
                    <div className="mb-1 flex justify-between text-[0.68rem] text-[#ffffff]/70">
                      <span>{label}</span>
                      <span className="font-semibold text-[#7aa5f0]">
                        {score}
                      </span>
                    </div>
                    <div className="h-1.5 rounded-full bg-[#dce6f7]/10">
                      <motion.div
                        initial={{ width: 0 }}
                        whileInView={{ width: `${score}%` }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.9, delay: 0.4 }}
                        className="h-full rounded-full bg-[#7aa5f0]"
                      />
                    </div>
                  </div>
                ))}
              </div>
              <div className="mt-4 flex items-center justify-between rounded-xl bg-[#dce6f7]/10 px-3 py-2.5 text-[0.72rem] text-[#ffffff]/80">
                <span>Overall</span>
                <span className="font-bold text-[#7aa5f0]">94 · sent</span>
              </div>
              <p className="mt-3 text-[0.62rem] text-[#ffffff]/45">
                Candidates below 90 never reach your inbox.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ============ STATS STRIP (dark) ============ */}
      <section className="border-t border-[#dce6f7]/10 bg-[#0e1730] text-[#ffffff]">
        <div className="mx-auto grid max-w-6xl grid-cols-2 gap-px px-4 sm:px-6 md:grid-cols-4">
          {[
            { v: "90+", l: "The only score we send" },
            { v: "100", l: "Points. Every candidate" },
            { v: "3–5", l: "Candidates per shortlist" },
            { v: "AI", l: "Built & tested in-house" },
          ].map((s, i) => (
            <motion.div
              key={s.l}
              {...reveal}
              transition={{ duration: 0.5, delay: i * 0.06, ease: "easeOut" }}
              className="px-2 py-10 text-center md:py-14"
            >
              <p className="nyr-display !text-[clamp(2.2rem,5vw,3.4rem)] text-[#7aa5f0]">
                {s.v}
              </p>
              <p className="nyr-signal mt-2">{s.l}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ============ HOW IT WORKS (light) ============ */}
      <section id="protocol" className="nyr-light bg-[#ffffff] text-[#0e1730]">
        <div className="mx-auto max-w-6xl px-4 py-24 sm:px-6">
          <motion.div
            {...reveal}
            className="grid items-end gap-6 md:grid-cols-[1.1fr_.6fr]"
          >
            <div>
              <p className="nyr-eyebrow mb-4">The process</p>
              <h2 className="nyr-display">
                Find. Score. <em>Send.</em>
              </h2>
            </div>
            <p className="text-[0.95rem] leading-relaxed text-[#44506b]">
              Four steps. No noise. You meet only the candidates worth your
              time — and we stay until the offer is signed.
            </p>
          </motion.div>

          <div className="mt-14 border-t border-[rgba(29,78,216,0.28)]">
            {steps.map((step, i) => (
              <motion.div
                key={step.n}
                {...reveal}
                transition={{ duration: 0.5, delay: i * 0.06, ease: "easeOut" }}
                className="grid gap-3 border-b border-[rgba(29,78,216,0.28)] py-8 md:grid-cols-[80px_220px_1fr] md:items-baseline md:gap-8"
              >
                <span className="nyr-step-number">{step.n}</span>
                <h3 className="text-2xl font-semibold tracking-tight">
                  {step.title}
                </h3>
                <p className="max-w-[58ch] text-[0.95rem] leading-relaxed text-[#44506b]">
                  {step.body}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ============ SCORING BREAKDOWN (dark) ============ */}
      <section id="scoring" className="nyr-dark-section relative overflow-hidden">
        <div className="nyr-grid-noise absolute inset-0" />
        <div className="relative mx-auto max-w-6xl px-4 py-24 sm:px-6">
          <motion.div {...reveal} className="max-w-2xl">
            <p className="nyr-eyebrow mb-4">The rubric</p>
            <h2 className="nyr-display text-[#ffffff]">
              100 points. <em>Zero guessing.</em>
            </h2>
            <p className="nyr-lede mt-5">
              Every candidate walks the same gauntlet. No vibes, no gut
              feelings — a published scale, scored by humans, applied to
              everyone exactly the same way.
            </p>
          </motion.div>

          <div className="mt-14 grid gap-5 md:grid-cols-3">
            {rubric.map((r, i) => (
              <motion.div
                key={r.name}
                {...reveal}
                transition={{ duration: 0.5, delay: i * 0.08, ease: "easeOut" }}
                className="nyr-card p-7"
              >
                <div className="flex items-center justify-between">
                  <div className="flex size-11 items-center justify-center rounded-xl border border-[#dce6f7]/15 bg-[#dce6f7]/5">
                    <r.icon className="size-5 text-[#7aa5f0]" />
                  </div>
                  <span className="text-[0.7rem] font-extrabold uppercase tracking-[0.14em] text-[#7aa5f0]">
                    {r.weight}
                  </span>
                </div>
                <h3 className="mt-5 text-xl font-semibold text-[#ffffff]">
                  {r.name}
                </h3>
                <p className="mt-2 text-[0.9rem] leading-relaxed text-[#ffffff]/65">
                  {r.body}
                </p>
              </motion.div>
            ))}
          </div>

          <motion.div {...reveal} className="nyr-quote mt-16">
            <p className="text-xl font-medium leading-relaxed text-[#ffffff] sm:text-2xl">
              The best recruiting firms don't send you more candidates. They
              send you fewer — and every one is right.
            </p>
            <p className="nyr-signal mt-4">The Streamscale standard · 90+</p>
          </motion.div>
        </div>
      </section>

      {/* ============ WHO IT'S FOR (light) ============ */}
      <section id="who" className="nyr-light bg-[#ffffff] text-[#0e1730]">
        <div className="mx-auto max-w-6xl px-4 py-24 sm:px-6">
          <motion.div {...reveal} className="mx-auto max-w-2xl text-center">
            <p className="nyr-eyebrow mb-4">Who it's for</p>
            <h2 className="nyr-display">
              Who we <em>work with.</em>
            </h2>
          </motion.div>

          <div className="mt-14 grid gap-5 lg:grid-cols-2">
            {audiences.map((a, i) => (
              <motion.div
                key={a.title}
                {...reveal}
                transition={{ duration: 0.55, delay: i * 0.1, ease: "easeOut" }}
                className="flex flex-col rounded-2xl border border-[rgba(29,78,216,0.28)] bg-white p-8 shadow-[0_20px_60px_rgba(10,31,68,0.06)]"
              >
                <div className="flex size-12 items-center justify-center rounded-xl bg-[#0e1730]">
                  <a.icon className="size-5 text-[#7aa5f0]" />
                </div>
                <h3 className="mt-5 text-2xl font-semibold tracking-tight">
                  {a.title}
                </h3>
                <p className="mt-3 text-[0.95rem] leading-relaxed text-[#44506b]">
                  {a.body}
                </p>
                <ul className="mt-5 flex-1 space-y-3">
                  {a.points.map((p) => (
                    <li key={p} className="flex items-start gap-3 text-[0.92rem] leading-relaxed text-[#44506b]">
                      <Check className="mt-0.5 size-4 shrink-0 text-[#5b7fc7]" />
                      {p}
                    </li>
                  ))}
                </ul>
                <div className="mt-7">
                  <Link to={a.cta.to} className="nyr-primary-btn nyr-ink">
                    {a.cta.label} <ArrowRight className="size-4" />
                  </Link>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ============ AI SYSTEMS (dark) ============ */}
      <section className="nyr-dark-section relative overflow-hidden">
        <div
          className="absolute inset-0"
          style={{
            background:
              "radial-gradient(ellipse 55% 50% at 50% 0%, rgba(46,107,239,.14), transparent 60%)",
          }}
        />
        <div className="relative mx-auto max-w-6xl px-4 py-24 sm:px-6">
          <motion.div
            {...reveal}
            className="grid items-end gap-6 md:grid-cols-[1.1fr_.7fr]"
          >
            <div>
              <p className="nyr-eyebrow mb-4">Beyond recruiting</p>
              <h2 className="nyr-display text-[#ffffff]">
                We build and test <em>enterprise AI.</em>
              </h2>
            </div>
            <p className="text-[0.95rem] leading-relaxed text-[#ffffff]/65">
              It's not a side project — it's the reason our 90+ means
              something. We evaluate people the same way we evaluate machines.
            </p>
          </motion.div>

          <div className="mt-14 grid gap-5 md:grid-cols-3">
            {aiPoints.map((p, i) => (
              <motion.div
                key={p.title}
                {...reveal}
                transition={{ duration: 0.5, delay: i * 0.08, ease: "easeOut" }}
                className="nyr-card p-7"
              >
                <p.icon className="size-6 text-[#7aa5f0]" />
                <h3 className="mt-4 text-lg font-semibold text-[#ffffff]">
                  {p.title}
                </h3>
                <p className="mt-2 text-[0.9rem] leading-relaxed text-[#ffffff]/65">
                  {p.body}
                </p>
              </motion.div>
            ))}
          </div>

          <motion.div {...reveal} className="mt-12 flex flex-wrap items-center gap-6">
            <Link to="/benchmarks" className="nyr-primary-btn">
              See the benchmarks <ArrowUpRight className="size-4" />
            </Link>
            <a href="#protocol" className="nyr-text-link">
              Back to the process <span aria-hidden>↑</span>
            </a>
          </motion.div>
        </div>
      </section>

      {/* ============ FAQ (light) ============ */}
      <section className="nyr-light bg-[#ffffff] text-[#0e1730]">
        <div className="mx-auto max-w-4xl px-4 py-24 sm:px-6">
          <motion.div {...reveal}>
            <p className="nyr-eyebrow mb-4">Questions</p>
            <h2 className="nyr-display">
              Fair <em>ones.</em>
            </h2>
          </motion.div>

          <div className="mt-12 border-t border-[rgba(29,78,216,0.28)]">
            {faqs.map((f, i) => (
              <motion.details
                key={f.q}
                {...reveal}
                transition={{ duration: 0.4, delay: i * 0.05, ease: "easeOut" }}
                className="group border-b border-[rgba(29,78,216,0.28)] py-6"
              >
                <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-lg font-semibold tracking-tight [&::-webkit-details-marker]:hidden">
                  {f.q}
                  <span className="nyr-step-number shrink-0 transition-transform group-open:rotate-45">
                    +
                  </span>
                </summary>
                <p className="mt-3 max-w-[62ch] text-[0.95rem] leading-relaxed text-[#44506b]">
                  {f.a}
                </p>
              </motion.details>
            ))}
          </div>
        </div>
      </section>

      {/* ============ FINAL CTA (dark) ============ */}
      <section className="nyr-dark-section relative overflow-hidden">
        <div
          className="absolute inset-0"
          style={{
            background:
              "radial-gradient(ellipse 50% 60% at 50% 110%, rgba(46,107,239,.18), transparent 60%)",
          }}
        />
        <div className="relative mx-auto max-w-4xl px-4 py-28 text-center sm:px-6">
          <motion.h2
            {...reveal}
            className="nyr-display mx-auto max-w-[12ch] text-[#ffffff]"
          >
            A better way <em>to hire.</em>
          </motion.h2>
          <motion.p
            {...reveal}
            className="nyr-lede mx-auto mt-5 max-w-[44ch]"
          >
            Tell us the role. Meet only the 90+.
          </motion.p>
          <motion.div
            {...reveal}
            className="mt-9 flex flex-wrap items-center justify-center gap-6"
          >
            <Link to="/partner" className="nyr-primary-btn">
              Start hiring <ArrowRight className="size-4" />
            </Link>
            <Link to="/jobs" className="nyr-text-link">
              View open jobs <ArrowUpRight className="size-4" />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <NyrFooter />
    </div>
  );
}
