import { Link } from "react-router";
import { motion } from "framer-motion";
import {
  ArrowRight,
  ArrowUpRight,
  Bot,
  Briefcase,
  Building2,
  Check,
  Code2,
  FileText,
  ShieldCheck,
  Sparkles,
} from "lucide-react";
import { NyrNav, NyrFooter } from "@/components/NyrLayout";

const reveal = {
  initial: { opacity: 0, y: 18 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-60px" },
  transition: { duration: 0.55, ease: "easeOut" as const },
};

const steps = [
  {
    n: "01",
    title: "Find",
    body: "We post the role and hunt down candidates ourselves — human recruiters doing real sourcing, not keyword filters. Every pipeline is built by hand for the specific role.",
  },
  {
    n: "02",
    title: "Score",
    body: "Every single candidate gets scored on our 100-point scale: resume, work experience, and technical skills. No exceptions, no gut feelings.",
  },
  {
    n: "03",
    title: "Send",
    body: "Only candidates scoring 90+ reach your team. Everyone else never makes it past us — your inbox stays clean, your time stays yours.",
  },
  {
    n: "04",
    title: "Support",
    body: "We stay in the loop through interviews and offer. If AI can automate part of the work instead of hiring for it, we'll build that too.",
  },
];

const rubric = [
  {
    icon: FileText,
    name: "Resume",
    weight: "30 pts",
    body: "Trajectory, impact, and signal — not keyword soup. We read every line ourselves and look for people who shipped things that mattered.",
  },
  {
    icon: Briefcase,
    name: "Experience",
    weight: "30 pts",
    body: "Where they've worked, what they owned, and how long they stayed. Real companies, real responsibility, real results.",
  },
  {
    icon: Code2,
    name: "Technical skills",
    weight: "40 pts",
    body: "The heaviest slice. Hands-on evaluation of what they can actually build — informed by our own AI systems work, so the bar is a working bar.",
  },
];

const audiences = [
  {
    icon: Building2,
    title: "Startups hiring now",
    body: "You need great people fast, but don't have the time or pipeline to sort hundreds of resumes. We handle the hunt and hand you a shortlist of only the strongest candidates.",
    points: [
      "No in-house recruiter needed — we are your recruiting team",
      "3 to 5 pre-scored candidates instead of a pile of maybes",
      "Full scorecards attached so you know why each person made the cut",
      "Works for engineering, ops, GTM — any role you'd trust a human with",
    ],
    cta: { label: "Start hiring", to: "/partner" },
  },
  {
    icon: Sparkles,
    title: "Founders who've been burned",
    body: "You've tried job boards, agencies, and AI tools. What showed up was noise. We built our scoring system so we could promise a bar instead of a volume discount.",
    points: [
      "A published 100-point rubric, applied the same way to everyone",
      "If AI can do part of the role, we'll tell you before you hire for it",
      "One flat conversation about the role — not a sales funnel",
      "We benchmark enterprise AI ourselves, so our bar is a working bar",
    ],
    cta: { label: "Partner with us", to: "/partner" },
  },
];

const aiPoints = [
  {
    icon: Bot,
    title: "We build enterprise AI",
    body: "Custom agents and automation for real business workflows — deployed, monitored, and owned by you. Not demos. Systems that survive production.",
  },
  {
    icon: ShieldCheck,
    title: "We test AI honestly",
    body: "Independent benchmarks across industries. Real simulations, pass rates, failure analysis. If an AI can't do the job, we publish that too.",
  },
  {
    icon: Sparkles,
    title: "It sharpens our hiring",
    body: "Because we build and evaluate AI systems ourselves, we know exactly what 'great' looks like — and we score every candidate against that same bar.",
  },
];

const faqs = [
  {
    q: "What does the 100-point scale actually measure?",
    a: "Three things, weighted: resume (30), work experience (30), and technical skills (40). Every candidate is scored on all three by a human recruiter, and you see the full breakdown for anyone we send you.",
  },
  {
    q: "Why only 90+?",
    a: "Because you don't need more candidates — you need the right ones. Filtering to 90+ means we send you a handful of people worth meeting instead of a pile of maybes. Fewer interviews, faster hires, better outcomes.",
  },
  {
    q: "How is this different from an AI recruiter tool?",
    a: "It's the opposite. Real humans source and read every candidate. We use AI systems on the evaluation side — built and tested in-house — to make our scoring sharper, not to spam you with autogenerated matches.",
  },
  {
    q: "What if we don't need a hire at all?",
    a: "That's the other half of our business. We build and test enterprise AI systems, and sometimes the honest answer is that part of the role can be automated. We'll tell you which, and build it if you want.",
  },
  {
    q: "How do we get started?",
    a: "Tell us about the role through the partner form. We build the pipeline, start scoring, and your first 90+ candidates typically arrive within days — with the full scorecard attached.",
  },
];

const scores = [
  { label: "Resume", value: 94 },
  { label: "Experience", value: 92 },
  { label: "Technical", value: 96 },
];

export default function Landing() {
  return (
    <div className="nyr">
      <NyrNav />

      {/* ============ HERO ============ */}
      <section className="nyr-hero">
        <div className="nyr-grid" />
        <div className="relative mx-auto grid min-h-[calc(100svh-68px)] max-w-6xl items-center gap-14 px-4 py-24 sm:px-6 lg:grid-cols-[1.05fr_.75fr]">
          <div>
            <motion.div {...reveal} className="nyr-eyebrow mb-7">
              <span className="nyr-status-dot" />
              Recruitment for the AI era
            </motion.div>

            <motion.h1
              {...reveal}
              transition={{ duration: 0.55, delay: 0.08, ease: "easeOut" }}
              className="nyr-display mb-7"
            >
              We find the best people <em>for the job.</em>
            </motion.h1>

            <motion.p
              {...reveal}
              transition={{ duration: 0.55, delay: 0.14, ease: "easeOut" }}
              className="nyr-lede mb-9 max-w-[46ch]"
            >
              Streamscale hunts down top candidates, scores every one on a
              100-point scale — resume, experience, technical skills — and only
              sends you the 90+. We also build and test enterprise AI systems,
              so we know exactly what great looks like.
            </motion.p>

            <motion.div
              {...reveal}
              transition={{ duration: 0.55, delay: 0.2, ease: "easeOut" }}
              className="flex flex-wrap items-center gap-6"
            >
              <Link to="/partner" className="nyr-btn nyr-btn-primary">
                Find your next hire <ArrowRight className="size-4" />
              </Link>
              <a href="#scoring" className="nyr-link text-white/80 hover:text-white">
                See how we score <span aria-hidden>↓</span>
              </a>
            </motion.div>

            <motion.div
              {...reveal}
              transition={{ duration: 0.55, delay: 0.26, ease: "easeOut" }}
              className="nyr-signal mt-14 flex flex-wrap gap-x-8 gap-y-2"
            >
              <span>Humans placed by humans.</span>
              <span>Only 90+ scorers reach your team.</span>
            </motion.div>
          </div>

          {/* Candidate scorecard */}
          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.7, delay: 0.15, ease: "easeOut" }}
            className="relative hidden place-items-center lg:grid"
          >
            <div className="nyr-halo" />
            <div className="nyr-card relative w-full max-w-[290px] rounded-[20px] p-6 backdrop-blur-sm">
              <div className="nyr-score-row">
                <span>9:41</span>
                <span>•••</span>
              </div>

              <p className="nyr-eyebrow mt-7 !text-[0.62rem]">Candidate scorecard</p>
              <h3 className="mt-2 text-xl font-semibold text-white">Senior AI Engineer</h3>

              <div className="mt-6 space-y-4">
                {scores.map((score, i) => (
                  <div key={score.label}>
                    <div className="nyr-score-row mb-1.5">
                      <span>{score.label}</span>
                      <span className="font-semibold text-[#93b4f5]">{score.value}</span>
                    </div>
                    <div className="nyr-score-track">
                      <motion.div
                        initial={{ width: 0 }}
                        whileInView={{ width: `${score.value}%` }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.9, delay: 0.4 + i * 0.1 }}
                        className="nyr-score-fill"
                      />
                    </div>
                  </div>
                ))}
              </div>

              <div className="mt-6 flex items-center justify-between rounded-xl bg-white/10 px-4 py-3 text-[0.78rem] text-white/80">
                <span>Overall</span>
                <span className="font-semibold text-[#93b4f5]">94 · sent</span>
              </div>

              <p className="nyr-signal mt-4 !text-[0.68rem]">
                Candidates below 90 never reach your inbox.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ============ STATS ============ */}
      <section className="border-y border-border bg-white">
        <div className="mx-auto grid max-w-6xl grid-cols-2 gap-px px-4 sm:px-6 md:grid-cols-4">
          {[
            { v: "90+", l: "The only score we send" },
            { v: "100", l: "Points. Every candidate" },
            { v: "3–5", l: "Candidates per shortlist" },
            { v: "AI", l: "Built & tested in-house" },
          ].map((stat, i) => (
            <motion.div
              key={stat.l}
              {...reveal}
              transition={{ duration: 0.5, delay: i * 0.06, ease: "easeOut" }}
              className="px-2 py-12 text-center"
            >
              <p className="nyr-display-md text-[var(--nyr-blue)]">{stat.v}</p>
              <p className="nyr-signal mt-2">{stat.l}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ============ PROCESS ============ */}
      <section id="protocol" className="nyr-section bg-white">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <motion.div
            {...reveal}
            className="grid items-end gap-8 md:grid-cols-[1.1fr_.6fr]"
          >
            <div>
              <p className="nyr-eyebrow mb-4">The process</p>
              <h2 className="nyr-display-md">
                Find. Score. <em>Send.</em>
              </h2>
            </div>
            <p className="nyr-lede">
              Four steps. No noise. You meet only the candidates worth your
              time — and we stay until the offer is signed.
            </p>
          </motion.div>

          <div className="nyr-divide mt-14">
            {steps.map((step, i) => (
              <motion.div
                key={step.n}
                {...reveal}
                transition={{ duration: 0.5, delay: i * 0.06, ease: "easeOut" }}
                className="grid gap-3 py-8 md:grid-cols-[70px_220px_1fr] md:items-baseline md:gap-8"
              >
                <span className="nyr-step">{step.n}</span>
                <h3 className="text-2xl font-semibold tracking-tight">{step.title}</h3>
                <p className="nyr-lede max-w-[58ch] text-[0.95rem]">{step.body}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ============ RUBRIC ============ */}
      <section id="scoring" className="nyr-section nyr-hero">
        <div className="nyr-grid" />
        <div className="relative mx-auto max-w-6xl px-4 sm:px-6">
          <motion.div {...reveal} className="max-w-2xl">
            <p className="nyr-eyebrow mb-4">The rubric</p>
            <h2 className="nyr-display-md">
              100 points. <em>Zero guessing.</em>
            </h2>
            <p className="nyr-lede mt-5">
              Every candidate walks the same gauntlet. No vibes, no gut
              feelings — a published scale, scored by humans, applied to
              everyone exactly the same way.
            </p>
          </motion.div>

          <div className="mt-14 grid gap-5 md:grid-cols-3">
            {rubric.map((item, i) => (
              <motion.div
                key={item.name}
                {...reveal}
                transition={{ duration: 0.5, delay: i * 0.08, ease: "easeOut" }}
                className="nyr-card p-7"
              >
                <div className="flex items-center justify-between">
                  <div className="flex size-11 items-center justify-center rounded-xl border border-white/15 bg-white/5">
                    <item.icon className="size-5 text-[#93b4f5]" />
                  </div>
                  <span className="nyr-step !text-[#93b4f5]">{item.weight}</span>
                </div>
                <h3 className="mt-5 text-xl font-semibold text-white">{item.name}</h3>
                <p className="mt-2 text-[0.9rem] leading-relaxed text-white/65">{item.body}</p>
              </motion.div>
            ))}
          </div>

          <motion.div {...reveal} className="nyr-quote mt-20 max-w-3xl">
            <p className="text-xl font-medium leading-relaxed text-white sm:text-2xl">
              The best recruiting firms don't send you more candidates. They
              send you fewer — and every one is right.
            </p>
            <p className="nyr-signal mt-4">The Streamscale standard · 90+</p>
          </motion.div>
        </div>
      </section>

      {/* ============ WHO WE WORK WITH ============ */}
      <section id="who" className="nyr-section bg-white">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <motion.div {...reveal} className="mx-auto max-w-2xl text-center">
            <p className="nyr-eyebrow mb-4">Who it's for</p>
            <h2 className="nyr-display-md">
              Who we <em>work with.</em>
            </h2>
          </motion.div>

          <div className="mt-14 grid gap-5 lg:grid-cols-2">
            {audiences.map((audience, i) => (
              <motion.div
                key={audience.title}
                {...reveal}
                transition={{ duration: 0.55, delay: i * 0.1, ease: "easeOut" }}
                className="nyr-card flex flex-col p-8"
              >
                <div className="flex size-12 items-center justify-center rounded-xl bg-[var(--nyr-ink)]">
                  <audience.icon className="size-5 text-[#93b4f5]" />
                </div>
                <h3 className="mt-5 text-2xl font-semibold tracking-tight">
                  {audience.title}
                </h3>
                <p className="nyr-lede mt-3 text-[0.95rem]">{audience.body}</p>
                <ul className="mt-6 flex-1 space-y-3">
                  {audience.points.map((point) => (
                    <li
                      key={point}
                      className="flex items-start gap-3 text-[0.92rem] leading-relaxed text-muted-foreground"
                    >
                      <Check className="mt-0.5 size-4 shrink-0 text-[var(--nyr-blue)]" />
                      {point}
                    </li>
                  ))}
                </ul>
                <div className="mt-8">
                  <Link to={audience.cta.to} className="nyr-btn nyr-btn-light">
                    {audience.cta.label} <ArrowRight className="size-4" />
                  </Link>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ============ AI SYSTEMS ============ */}
      <section className="nyr-section nyr-hero">
        <div className="nyr-grid" />
        <div className="relative mx-auto max-w-6xl px-4 sm:px-6">
          <motion.div
            {...reveal}
            className="grid items-end gap-8 md:grid-cols-[1.1fr_.7fr]"
          >
            <div>
              <p className="nyr-eyebrow mb-4">Beyond recruiting</p>
              <h2 className="nyr-display-md">
                We build and test <em>enterprise AI.</em>
              </h2>
            </div>
            <p className="nyr-lede">
              It's not a side project — it's the reason our 90+ means something.
              We evaluate people the same way we evaluate machines.
            </p>
          </motion.div>

          <div className="mt-14 grid gap-5 md:grid-cols-3">
            {aiPoints.map((point, i) => (
              <motion.div
                key={point.title}
                {...reveal}
                transition={{ duration: 0.5, delay: i * 0.08, ease: "easeOut" }}
                className="nyr-card p-7"
              >
                <point.icon className="size-6 text-[#93b4f5]" />
                <h3 className="mt-4 text-lg font-semibold text-white">{point.title}</h3>
                <p className="mt-2 text-[0.9rem] leading-relaxed text-white/65">{point.body}</p>
              </motion.div>
            ))}
          </div>

          <motion.div {...reveal} className="mt-12 flex flex-wrap items-center gap-6">
            <Link to="/benchmarks" className="nyr-btn nyr-btn-primary">
              See the benchmarks <ArrowUpRight className="size-4" />
            </Link>
            <a href="#protocol" className="nyr-link text-white/80 hover:text-white">
              Back to the process <span aria-hidden>↑</span>
            </a>
          </motion.div>
        </div>
      </section>

      {/* ============ FAQ ============ */}
      <section className="nyr-section bg-white">
        <div className="mx-auto max-w-4xl px-4 sm:px-6">
          <motion.div {...reveal}>
            <p className="nyr-eyebrow mb-4">Questions</p>
            <h2 className="nyr-display-md">
              Fair <em>ones.</em>
            </h2>
          </motion.div>

          <div className="nyr-divide mt-12">
            {faqs.map((faq, i) => (
              <motion.details
                key={faq.q}
                {...reveal}
                transition={{ duration: 0.4, delay: i * 0.05, ease: "easeOut" }}
                className="group py-6"
              >
                <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-lg font-semibold tracking-tight [&::-webkit-details-marker]:hidden">
                  {faq.q}
                  <span className="nyr-step shrink-0 transition-transform group-open:rotate-45">
                    +
                  </span>
                </summary>
                <p className="nyr-lede mt-3 max-w-[62ch] text-[0.95rem]">{faq.a}</p>
              </motion.details>
            ))}
          </div>
        </div>
      </section>

      {/* ============ CTA ============ */}
      <section className="nyr-hero">
        <div className="nyr-grid" />
        <div className="relative mx-auto max-w-4xl px-4 py-32 text-center sm:px-6">
          <motion.h2 {...reveal} className="nyr-display mx-auto max-w-[12ch]">
            A better way <em>to hire.</em>
          </motion.h2>
          <motion.p {...reveal} className="nyr-lede mx-auto mt-6 max-w-[42ch]">
            Tell us the role. Meet only the 90+.
          </motion.p>
          <motion.div
            {...reveal}
            className="mt-10 flex flex-wrap items-center justify-center gap-6"
          >
            <Link to="/partner" className="nyr-btn nyr-btn-primary">
              Start hiring <ArrowRight className="size-4" />
            </Link>
            <Link to="/jobs" className="nyr-link text-white/80 hover:text-white">
              View open jobs <ArrowUpRight className="size-4" />
            </Link>
          </motion.div>
        </div>
      </section>

      <NyrFooter />
    </div>
  );
}
